### PR TITLE
bump: bump up notation-core-go for `release-1.3` branch

### PR DESCRIPTION
**Pull request by Two-Hearts**
This PR targets on `release-1.3` branch.

### CODE REVIEW

**Comment by JeyJeyGao** [comment]
Should this PR be a cherry-pick of #488

**Comment by Two-Hearts** [comment]
> Should this PR be a cherry-pick of #488

It doesn't have to be a cherry pick. In the previous cherry pick, I got a conflict for the bump up.

**Review by JeyJeyGao — APPROVED** [review]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by vaninrao10 — APPROVED** [review]
LGTM

**Pull request merged**
