### PR TITLE
bump: bump up notation-core-go and signingAgent

### PR DESCRIPTION
**Pull request by Two-Hearts**
This PR targets on main branch.

### CODE REVIEW

**Review by JeyJeyGao — APPROVED** [review]
LGTM

**Review by shizhMSFT — CHANGES_REQUESTED** [review]
Is this PR succeeded by #442 ?

**Comment by Two-Hearts** [comment]
> Is this PR succeeded by #442 ?

No, this PR targets on `main` branch as shown at the top of the PR. Whereas, #442 targets at the `release-1.2` branch. As we discussed, there will be another vote PR for `release-1.2` branch later.

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by JeyJeyGao — APPROVED** [review]
LGTM

**Review by vaninrao10 — APPROVED** [review]
LGTM

**Pull request merged**
