### PR TITLE
test: add fuzz test

### PR DESCRIPTION
**Pull request by AdamKorcz**
Adds a fuzz test from cncf-fuzzing: https://github.com/cncf/cncf-fuzzing/blob/main/projects/notary/fuzz_pkix_test.go

### CODE REVIEW

**Comment by yizha1** [comment]
@AdamKorcz You may need to merge the latest changes and sign-off the commit again.

**Comment by Two-Hearts** [comment]
Hi @AdamKorcz, same to the notation-core-go PR, you will need to use the `-S` flag in your git command to sign the commit (needs to be capital `S`). The `-s` or `--signoff` flags only signoff the commit but not signing it.

**Comment by AdamKorcz** [comment]
Have signed the commit.

**Review by Two-Hearts — APPROVED** [review]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by priteshbandi — APPROVED** [review]
LGTM

**Pull request merged**
