### PR TITLE
build: bump image-spec to v1.1.0-rc.3 and oras-go to v2.1.0

### PR DESCRIPTION
**Pull request by shizhMSFT**
Closes #305
Closes #307

### CODE REVIEW

**Comment by sajayantony** [comment]
Should we remove the ability to create artifactManifest mediaType and only allow for read with a deprecation warning?

**Comment by rchincha** [comment]
Also, under "internal/" so external imports don't work yet.

**Comment by FeynmanZhou** [comment]
> Should we remove the ability to create artifactManifest mediaType and only allow for read with a deprecation warning?

Agree with  @sajayantony. This change is also supposed to be considered in Notation CLI.

**Comment by shizhMSFT** [comment]
> Should we remove the ability to create artifactManifest mediaType and only allow for read with a deprecation warning?

This is partially addressed by #308. We might need more discussions on the warning and it can be done in another PR.

**Review by JeyJeyGao — APPROVED** [review]
LGTM

**Pull request merged**
