### PR TITLE
Added CODEOWNERS and MAINTAINERS files

### PR DESCRIPTION
**Pull request by toddysm**
Signed-off-by: Toddy Mladenov <toddysm@gmail.com>

This PR combines all the changes from the following PRs for updating the maintainers for *notaryproject/notation-go* sub-project:
[Add Junjie Gao](https://github.com/notaryproject/notation-go/pull/265) #265 
[Add Milind Gokarn](https://github.com/notaryproject/notation-go/pull/259) #259 
[Add Patrick Zheng](https://github.com/notaryproject/notation-go/pull/264) #264 
[Add Pritesh Bandi](https://github.com/notaryproject/notation-go/pull/258) #258 
[Add Rakesh Gariganti](https://github.com/notaryproject/notation-go/pull/260) #260 
[Add Shiwei Zhang](https://github.com/notaryproject/notation-go/pull/263) #263 

The proposal is to abandon the above PRs and merge only this one.

### CODE REVIEW

**Review by vaninrao10 — CHANGES_REQUESTED** [review]
Rakesh Gokarn <garigant@amazon.com> (@rgnote) need to be changed to Rakesh Gariganti<garigant@amazon.com> (@rgnote)

**Review by vaninrao10 — APPROVED** [review]
LGTM

**Comment by toddysm** [comment]
Linking the issue #249

**Review by JeyJeyGao — APPROVED** [review]
LGTM but IANAM

**Review by patrickzheng200 — APPROVED** [review]
LGTM but IANAM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by yizha1 — APPROVED** [review]
LGTM but IANAM

**Review by NiazFK — APPROVED** [review]
LGTM

**Review by gokarnm — APPROVED** [review]
LGTM but IANAM

**Review by priteshbandi — APPROVED** [review]
LGTM

**Review by iamsamirzon — APPROVED** [review]

**Review by SteveLasker — APPROVED** [review]
LGTM
Welcome new maintainers!

**Review by justincormack — APPROVED** [review]

**Pull request merged**
