### PR TITLE
fix: quick fix typo in error msg

### PR DESCRIPTION
**Pull request by Two-Hearts**

### CODE REVIEW

**Review by JeyJeyGao — APPROVED** [review]
LGTM

**Review by binbin-li — APPROVED** [review]
lgtm

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Comment by shizhMSFT** [comment]
@Two-Hearts Should we scan all three repos for `sing`?

**Comment by Two-Hearts** [comment]
> @Two-Hearts Should we scan all three repos for `sing`?

@shizhMSFT good idea, I will scan the other two repos next Monday. For notation-go, I've already done that.

**Review by priteshbandi — APPROVED** [review]
LGTM

**Pull request merged**
