### PR TITLE
fix:fix broken verification unit tests

### PR DESCRIPTION
**Pull request by chloeyin**
1. Remove `VerificationPlugin` and `VerificationPluginMinVersion` from plugin's critical attribute
2. Fix broken tests (mostly error msg changes)

Signed-off-by: zaihaoyin <zaihaoyin@microsoft.com>

### CODE REVIEW

**Review by patrickzheng200 — COMMENTED** [review]
verifier_test.go line 588 duplicates with line 589, please remove one of them.

**Comment by patrickzheng200** [comment]
In verification/helpers_test.go, line 50 and line 78, err variable is not used. 
In verification/types.go, the getPluginConfig function's 2nd argument "config" is not being used.

**Comment by chloeyin** [comment]
> 

For `ioutil.WriteFile` in tests, should I handle the error, or just ignore them?

**Comment by chloeyin** [comment]
> In verification/helpers_test.go, line 50 and line 78, err variable is not used. In verification/types.go, the getPluginConfig function's 2nd argument "config" is not being used.

For `ioutil.WriteFile` in tests, should I handle the error, or just ignore them?

**Comment by patrickzheng200** [comment]
> > In verification/helpers_test.go, line 50 and line 78, err variable is not used. In verification/types.go, the getPluginConfig function's 2nd argument "config" is not being used.
> 
> For `ioutil.WriteFile` in tests, should I handle the error, or just ignore them?

I think we are handling all golang errors in our projects.

**Comment by JeyJeyGao** [comment]
LGTM

**Review by patrickzheng200 — APPROVED** [review]
LGTM

**Comment by chloeyin** [comment]
> > > In verification/helpers_test.go, line 50 and line 78, err variable is not used. In verification/types.go, the getPluginConfig function's 2nd argument "config" is not being used.
> > 
> > 
> > For `ioutil.WriteFile` in tests, should I handle the error, or just ignore them?
> 
> I think we are handling all golang errors in our projects.

Updated

**Review by binbin-li — APPROVED** [review]
lgtm

**Pull request merged**
