### PR TITLE
resolving remote signature envelope digest as blob instead of manifest

### LINKED ISSUE #88: Remote signature envelope digest should be resolved as Blob instead of Manifest
This issue is paired with Notation issue [#258](https://github.com/notaryproject/notation/issues/258).

### PR DESCRIPTION
**Pull request by patrickzheng200**
Signed-off-by: Patrick Zheng <patrickzheng@microsoft.com>

Resolves #88

### CODE REVIEW

**Comment by chloeyin** [comment]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Comment by rgnote** [comment]
I fed this in https://github.com/notaryproject/notation-go/pull/79

**Comment by shizhMSFT** [comment]
> I fixed this in #79

@rgnote #79 is a big PR and it is better to have separate PRs like this one. Let's merge this fix so that it can unblock others.

**Comment by rgnote** [comment]
> > I fixed this in #79
> 
> @rgnote #79 is a big PR and it is better to have separate PRs like this one. Let's merge this fix so that it can unblock others.

Sure. @patrickzheng200 Can you update the method name to `GetBlob` so that it accurately describes the method's functionality? We need to update the doc comments appropriately as well. Take a look at my changes in https://github.com/notaryproject/notation-go/pull/79/files for reference.

**Review by rgnote — APPROVED** [review]

**Comment by rgnote** [comment]
@patrickzheng200 You need to update [the interface](https://github.com/notaryproject/notation-go/blob/main/registry/interface.go#L16) as well.

**Comment by patrickzheng200** [comment]
> @patrickzheng200 You need to update [the interface](https://github.com/notaryproject/notation-go/blob/main/registry/interface.go#L16) as well.

Code updated.

**Review by rgnote — APPROVED** [review]

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Pull request merged**
