### PR TITLE
chore: cherry pick fixes from `main`

### PR DESCRIPTION
**Pull request by Two-Hearts**
This PR cherry picks from main to release-1.3. This is for v1.3.0-rc.2 release.

This PR targets on branch `release-1.3`.

### CODE REVIEW

**Review by JeyJeyGao — DISMISSED** [review]
LGTM. Compared commit history and diff against main branch.

**Review by shizhMSFT — COMMENTED** [review]
The commit e723406e09cdb3d7bbc140dfaa3d1c0e5affa1ea is required to be backported.

**Review by JeyJeyGao — DISMISSED** [review]
LGTM

**Comment by Two-Hearts** [comment]
> The commit [e723406](https://github.com/notaryproject/notation-go/commit/e723406e09cdb3d7bbc140dfaa3d1c0e5affa1ea) is required to be backported.

Updated.

**Comment by shizhMSFT** [comment]
Should cherry pick the following commits https://github.com/notaryproject/notation-go/compare/84c2ec076201697ad05e5315444812f824dad56b...95bac0082974676df4b299a87f0b600740008eda. Since #469 has merge conflicts, the related commit is covered by #489

**Review by shizhMSFT — CHANGES_REQUESTED** [review]
dd73327973887846ffea07994250f1e3043be790 should not be in this PR. Also, 11866a54a0d0d434d418beaa909a804efc5b7733 is missed.

Please create a new PR for bumping `notation-core-go` and merge after this PR.

**Comment by Two-Hearts** [comment]
> [dd73327](https://github.com/notaryproject/notation-go/commit/dd73327973887846ffea07994250f1e3043be790) should not be in this PR. Also, [11866a5](https://github.com/notaryproject/notation-go/commit/11866a54a0d0d434d418beaa909a804efc5b7733) is missed.
> 
> Please create a new PR for bumping `notation-core-go` and merge after this PR.

@shizhMSFT removed `dd73327`. However, cherry picking `11866a5` leads to conflict, so it has to be dropped. Will create another PR to bump up the dependencies.

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by JeyJeyGao — APPROVED** [review]
LGTM

**Review by vaninrao10 — APPROVED** [review]
LGTM

**Pull request merged**
