### PR TITLE
Add Rakesh Gariganti as notation maintainer

### PR DESCRIPTION
**Pull request by vaninrao10**
Add Pritesh Bandi as a seed maintainer of Notation based on [their](https://github.com/notaryproject/notation-go/commits?author=rgnote) activity as per - https://github.com/notaryproject/notation-go/issues/249

Signed-off-by: vaninrao10 <111005862+vaninrao10@users.noreply.github.com>

### CODE REVIEW

**Review by priteshbandi — APPROVED** [review]
LGTM but IANAM

**Review by yizha1 — APPROVED** [review]
LGTM

**Comment by iamsamirzon** [comment]
LGTM but IANAM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by patrickzheng200 — APPROVED** [review]
LGTM but IANAM

**Review by JeyJeyGao — APPROVED** [review]
LGTM but IANAM

**Review by binbin-li — APPROVED** [review]
LGTM but IANAM

**Review by gokarnm — APPROVED** [review]
LGTM but IANAM

**Comment by yizha1** [comment]
Close as aggregated PR https://github.com/notaryproject/notation-go/pull/272 was merged

**Pull request closed without merging**
