### PR TITLE
chore: backport #469 for updating logs

### PR DESCRIPTION
**Pull request by Two-Hearts**
This PR is for branch `release-1.3`.

### CODE REVIEW

**Review by JeyJeyGao — APPROVED** [review]
LGTM

**Review by JeyJeyGao — APPROVED** [review]
LGTM

**Comment by shizhMSFT** [comment]
Referencing:
- #469

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by vaninrao10 — APPROVED** [review]
LGTM

**Pull request merged**
