### PR TITLE
Add Pritesh Bandi as notation maintainer

### PR DESCRIPTION
**Pull request by vaninrao10**
Add Pritesh Bandi as a seed maintainer of Notation based on [their](https://github.com/notaryproject/notation-go/commits?author=priteshbandi) activity as per - https://github.com/notaryproject/notation-go/issues/249

Signed-off-by: Vani Rao <vaninrao@amazon.com>

### CODE REVIEW

**Comment by iamsamirzon** [comment]
LGTM but IANAM

**Review by toddysm — APPROVED** [review]
LGTM but IANAM

**Review by patrickzheng200 — APPROVED** [review]
LGTM but IANAM

**Review by JeyJeyGao — APPROVED** [review]
LGTM but IANAM

**Review by binbin-li — APPROVED** [review]
LGTM but IANAM

**Review by gokarnm — APPROVED** [review]
LGTM but IANAM

**Review by iamsamirzon — APPROVED** [review]

**Comment by yizha1** [comment]
Close as aggregated PR https://github.com/notaryproject/notation-go/pull/272 was merged

**Pull request closed without merging**
