### PR TITLE
bump: update notation-core-go dependency

### PR DESCRIPTION
**Pull request by priteshbandi**
Update notation-core-go dependency

### CODE REVIEW

**Review by shizhMSFT — DISMISSED** [review]
LGTM

**Comment by shizhMSFT** [comment]
We can remove this test 

https://github.com/notaryproject/notation-go/blob/064887e1ee5b8401fdaa1373d4a93bf16691a31e/signer/signer_test.go#L171

as we don't support timestamp in rc.2.

**Review by SteveLasker — DISMISSED** [review]
LGTM

**Review by patrickzheng200 — APPROVED** [review]
LGTM

**Review by SteveLasker — APPROVED** [review]
LGTM

**Review by vaninrao10 — APPROVED** [review]
LGTM

**Pull request merged**
