### PR TITLE
update: removed Sign with OCI artifact manifest

### PR DESCRIPTION
**Pull request by Two-Hearts**
This PR removes notation-go `Sign`'s support of OCI artifact manifest as it is removed from [image-spec v1.0.0-rc.3](https://github.com/opencontainers/image-spec/releases/tag/v1.1.0-rc.3). In other words, Notation will only generate signatures stored as OCI image manifest in the future.
(Note: Notation can still consume signatures already stored as OCI artifact manifest for backwards compatibility.)

Related issue: https://github.com/notaryproject/notation/issues/660

### CODE REVIEW

**Review by shizhMSFT — DISMISSED** [review]
LGTM

**Review by JeyJeyGao — DISMISSED** [review]
LGTM

**Review by priteshbandi — COMMENTED** [review]
Can you please update below references of artifact manifest?
https://github.com/notaryproject/notation-go/blob/f9c78f53409825454928af87ecd3cc0deeb91607/registry/interface.go#L17

https://github.com/notaryproject/notation-go/blob/f9c78f53409825454928af87ecd3cc0deeb91607/internal/mock/mocks.go#L76

**Review by JeyJeyGao — APPROVED** [review]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Pull request merged**
