### PR TITLE
hash name fix

### PR DESCRIPTION
**Pull request by chloeyin**
Signed-off-by: zaihaoyin <zaihaoyin@microsoft.com>

This PR is related to this PR https://github.com/notaryproject/notation-core-go/pull/20 and this issue https://github.com/notaryproject/notation/issues/268.

### CODE REVIEW

**Comment by patrickzheng200** [comment]
lgtm

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Comment by gokarnm** [comment]
@chloeyin @shizhMSFT please check my comment on related [notation-core PR](https://github.com/notaryproject/notation-core-go/pull/20#issuecomment-1205529607). IMO we should update the spec in this case.

**Review by patrickzheng200 — APPROVED** [review]
LGTM

**Review by binbin-li — APPROVED** [review]
lgtm

**Pull request merged**
