### PR TITLE
Add Shiwei Zhang as notation-go maintainer

### PR DESCRIPTION
**Pull request by yizha1**
Add Shiwei Zhang (@shizhMSFT) as a seed maintainer of `notation-go` based on [their](https://github.com/notaryproject/notation-go/commits?author=shizhMSFT) activity as per - https://github.com/notaryproject/notation-go/issues/249

Signed-off-by: Yi Zha <yizha1@microsoft.com>

### CODE REVIEW

**Review by priteshbandi — APPROVED** [review]
LGTM but IANAM

**Comment by iamsamirzon** [comment]
LGTM but IANAM

**Review by patrickzheng200 — APPROVED** [review]
LGTM but IANAM

**Review by JeyJeyGao — APPROVED** [review]
LGTM but IANAM

**Review by toddysm — APPROVED** [review]
LGTM but IANAM

**Review by binbin-li — APPROVED** [review]
LGTM but IANAM

**Review by vaninrao10 — APPROVED** [review]
LGTM but IANAM

**Review by gokarnm — APPROVED** [review]
LGTM but IANAM

**Review by iamsamirzon — APPROVED** [review]

**Comment by yizha1** [comment]
Close as aggregated PR https://github.com/notaryproject/notation-go/pull/272 was merged

**Pull request closed without merging**
