### PR TITLE
Add Patrick Zheng as notation-go maintainer

### PR DESCRIPTION
**Pull request by yizha1**
Add Patrick Zheng (@patrickzheng200) as a seed maintainer of `notation-go` based on [their](https://github.com/notaryproject/notation-go/commits?author=patrickzheng200) activity as per - https://github.com/notaryproject/notation-go/issues/249

Signed-off-by: Yi Zha <yizha1@microsoft.com>

### CODE REVIEW

**Review by priteshbandi — APPROVED** [review]
LGTM but IANAM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by toddysm — APPROVED** [review]
LGTM but IANAM

**Review by JeyJeyGao — APPROVED** [review]
LGTM but IANAM

**Review by binbin-li — APPROVED** [review]
LGTM but IANAM

**Review by gokarnm — APPROVED** [review]
LGTM but IANAM

**Review by iamsamirzon — APPROVED** [review]

**Comment by yizha1** [comment]
Close as aggregated PR https://github.com/notaryproject/notation-go/pull/272 was merged

**Pull request closed without merging**
